version: '2'
services:
    spark:
        build:
            context: .
            dockerfile: Dockerfile
        image: itamtao/spark
        ports:
            - "8888:8888"
        volumes: 
            - ../:/home/tlin/notebooks