init:
    path_hdfs: file:/home/tlin/notebooks/data
    path_movie: Movies_and_TV.csv
    path_book: Books.csv
    path_music: raw/music.txt
    is_debug: True
    seed: 666666
    num_partition: 30
baseliner:
    num_atleast_rating: 5
    size_subset: 6666
    date_from: 2012
    date_to: 2013
    num_left: 0
    ratio_split: 0.2
    ratio_both: 0.8
    calculate_baseline_sim_method: adjust_cosine
    calculate_baseline_weighting: 50
extender:
    extend_among_topk: 10
generator:
    private_flag: False
    mapping_range: 1
    private_epsilon: 0.6
    private_rpo: 0.1
recommender:
    calculate_xmap_sim_method: cosine_item
    calculate_xmap_weighting: 50
    mapping_range: 10
    private_flag: False
    private_epsilon: 0.6
    private_rpo: 0.1
    decay_alpha: 0.03
